#################### default parameters ################################
# favicon module: https://github.com/gethugothemes/hugo-modules/tree/master/images#favicon-implementation
favicon = "images/favicon.png"
# logo module: https://github.com/gethugothemes/hugo-modules/tree/master/images#logo-implementation
logo = "images/logo.svg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "257px"
# if logo_webp set false, it will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Andromeda"

# footer information
footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# buy premium popup
buy_premium_popup = true

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# Main Sections
mainSections= ["blog"]

# contact information
[contact_info]
address = "2118 Thornridge Cir. Syracuse, Connecticut 35624"
phone = ["+704-555-0127", "+205-857-2321", "+002-569-6969"]
email = ["info@andromeda.io", "smith@anderson.io", "john@anderson.io"]

# Preloader 
# module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Buy Premium"
link = "https://gethugothemes.com/products/andromeda/"


# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["Hugo", "GetHugoThemes", "Themefisher"]
description = "Software and SAAS Landing Hugo Theme"
author = "Gethugothemes"
image = "images/og-image.jpg" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
# matomo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/matomo-analytics
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
# baidu module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/baidu-analytics
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
# plausible module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/plausible-analytics
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
# counter module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/counter-analytics
[counter]
enable = false
username = "" # your username

# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# crisp chat - module: https://github.com/gethugothemes/hugo-modules/tree/master/components/crisp-chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Helping teams in the world with focus"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
button = "Buy Premium"
button_link = "https://gethugothemes.com/products/andromeda/"
